PidFile=/tmp/zabbix_agent2.pid
LogType=console
LogFileSize=0
DebugLevel=3
Server=127.0.0.1
ServerActive=127.0.0.1:11051
Hostname=netology-agent-02
HostMetadata=linux
RefreshActiveChecks=60
Timeout=10
